desc: configs/descriptor/none.yaml
det: configs/detector/sift.yaml
matcher: configs/matcher/nn.yaml
filter: configs/lmcnet/lmcnet_sift_indoor.yaml
estimator: configs/estimator/rescale_ransac_1600.yaml
