type: lmcnet
name: lmcnet_sift_outdoor_geom

#############network###############
eta: 10.0
eta_learnable: true
geom_only: true
geom_feats_dim: 0
knn_num: 8

###############eval#############
eig_type: small_min
eig_dir: data/outdoor_eig_cache
prob_thresh: 0.95