type: lmcnet
name: lmcnet_sift_indoor_geom

#############network###############
eta: 10.0
eta_learnable: true
geom_only: true
geom_feats_dim: 0
knn_num: 8

###############eval#############
eig_type: small
eig_dir: data/indoor_eig_cache
prob_thresh: 0.9